INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME) VALUES ('Jack', 'Bauer', 'j.bauer@ctu.gov')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME) VALUES ('Chloe','O`Brian', 'c.obrian@ctu.gov')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME) VALUES ('Kim', 'Bauer', 'kim_bauer@gmail.com')
INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, USER_NAME) VALUES ('Tony', 'Almeida', 't.almeida@ctu.gov')

INSERT INTO GAME (CREATION_DATE) VALUES ('2019-08-03T03:15:00')
INSERT INTO GAME (CREATION_DATE) VALUES ('2019-08-03T03:16:00')
INSERT INTO GAME (CREATION_DATE) VALUES ('2019-08-03T03:16:00')
INSERT INTO GAME (CREATION_DATE) VALUES ('2019-08-03T03:16:00')
INSERT INTO GAME (CREATION_DATE) VALUES ('2019-08-03T03:16:00')


INSERT INTO GAME_PLAYER (CREATION_DATE, PLAYER_ID, GAME_ID) VALUES ('2019-08-03T03:16:00', 2, 1)
INSERT INTO GAME_PLAYER (CREATION_DATE, PLAYER_ID, GAME_ID) VALUES ('2019-08-03T03:16:00', 1, 2)
INSERT INTO GAME_PLAYER (CREATION_DATE, PLAYER_ID, GAME_ID) VALUES ('2019-08-03T03:16:00', 4, 3)
INSERT INTO GAME_PLAYER (CREATION_DATE, PLAYER_ID, GAME_ID) VALUES ( '2019-08-03T03:16:00', 4, 2)
INSERT INTO GAME_PLAYER (CREATION_DATE, PLAYER_ID, GAME_ID) VALUES ('2019-08-03T03:16:00', 1, 2)



INSERT INTO SHIP (GAME_PLAYER_ID, SHIP_TYPE) VALUES (2, 'CRUISER')
INSERT INTO SHIP (GAME_PLAYER_ID, SHIP_TYPE) VALUES (3, 'SUBMARINE')
INSERT INTO SHIP (GAME_PLAYER_ID, SHIP_TYPE) VALUES (1, 'DESTROYER')

INSERT INTO SHIP_LOCATIONS (SHIP_ID, LOCATIONS) VALUES (1, 'A1')
INSERT INTO SHIP_LOCATIONS (SHIP_ID, LOCATIONS) VALUES (1, 'A2')
INSERT INTO SHIP_LOCATIONS (SHIP_ID, LOCATIONS) VALUES (1, 'A3')
